name: Changed

on:
  workflow_call:
    outputs:
      matrix:
        description: "Changed matrix"
        value: ${{ jobs.changed-matrix.outputs.matrix }}

jobs:
  changed-matrix:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      matrix: ${{ steps.changed-script.outputs.matrix }}
    steps:
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v44.5.4
        with:
          dir_names: true
          matrix: true
          json: true
          escape_json: false
          files: |
             **.tf
             **.tfvars
      - uses: jannekem/run-python-script-action@v1.7
        id: changed-script
        with:
          script: |
            import os
            import json

            changed = ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
            names = {}
            for path in changed:
              name = path
              if path == ".":
                name = "root"
              name=name.replace("/", "_")
              names[path]=name
            
            out = json.dumps([{"path": k, "name": names[k]} for k in names])
            print(out)
            set_output("matrix", out)
