name: Release

on:
  pull_request:
    types: closed
    branches: [main]

jobs:
  changed:
    uses: ./.github/workflows/changed.yml
    secrets: inherit
    permissions:
      pull-requests: read
  matrix-job:
    name: "Release ${{ matrix.name }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      attestations: write
    needs: [changed]
    strategy:
      matrix:
        include: "${{ fromJSON(needs.changed.outputs.matrix) }}"
      fail-fast: false
    steps:
      - name: Tag
        id: tag
        uses: krogon/semver-release-action@v2.1.0
        with:
          release_branch: main
          tag_format: '${{ matrix.name }}-v%major%.%minor%.%patch%'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
